-- Run this once in the Supabase SQL Editor before starting the API.
create extension if not exists pgcrypto;
create table if not exists public.users (id uuid primary key default gen_random_uuid(), name text not null, email text not null unique, password text not null, role text not null check (role in ('student','teacher','admin')), lrn text, teacher_id text, admin_id text, address text, age integer check (age > 0), school_name text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.classes (id uuid primary key default gen_random_uuid(), class_name text not null unique, teacher uuid not null references public.users(id), time text, end_time text, day text not null, room_number text, students jsonb not null default '[]'::jsonb, is_archived boolean not null default false, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.activities (id uuid primary key default gen_random_uuid(), title text not null, description text, date timestamptz not null, score numeric, link text, attachment text, created_by uuid references public.users(id), class_id uuid not null references public.classes(id) on delete cascade, is_locked boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), title text not null, content text not null, posted_by uuid not null references public.users(id), class_id uuid not null references public.classes(id) on delete cascade, date_posted timestamptz not null default now(), comments jsonb not null default '[]'::jsonb, reactions jsonb not null default '[]'::jsonb, viewed_by jsonb not null default '[]'::jsonb, attachments jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.attendance (id uuid primary key default gen_random_uuid(), student_id uuid not null references public.users(id), class_id uuid not null references public.classes(id), status text not null check (status in ('Present','Absent','Late')), date timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (student_id, class_id, date));
create table if not exists public.modules (id uuid primary key default gen_random_uuid(), title text not null, description text, file_name text not null, file_path text not null, file_size bigint not null, mime_type text not null, cloudinary_url text, viewer_url text, public_id text, resource_type text default 'raw', class_id uuid not null references public.classes(id) on delete cascade, uploaded_by uuid not null references public.users(id), upload_date timestamptz not null default now(), is_active boolean not null default true, download_count integer not null default 0, tags jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.submissions (id uuid primary key default gen_random_uuid(), activity_id uuid not null references public.activities(id) on delete cascade, student_id uuid not null references public.users(id), submission_date timestamptz not null default now(), file_path text, file_name text, cloudinary_url text, cloudinary_public_id text, file_type text, file_size bigint, resource_type text, content text, status text not null default 'Submitted' check (status in ('Submitted','Resubmitted','Graded','Late')), score numeric, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (activity_id, student_id));
create table if not exists public.quizzes (id uuid primary key default gen_random_uuid(), class_id uuid not null references public.classes(id) on delete cascade, title text not null, questions jsonb not null default '[]'::jsonb, created_by uuid not null references public.users(id), due_date timestamptz, question_time integer not null default 30, created_at timestamptz not null default now());
create table if not exists public.quiz_submissions (id uuid primary key default gen_random_uuid(), quiz_id uuid not null references public.quizzes(id) on delete cascade, student_id uuid not null references public.users(id), answers jsonb not null default '[]'::jsonb, score numeric not null, submitted_at timestamptz not null default now(), unique (quiz_id, student_id));
create table if not exists public.visits (id uuid primary key default gen_random_uuid(), timestamp timestamptz not null default now(), user_agent text default '', ip_address text default '', page text not null, user_id uuid references public.users(id), session_id text default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists activities_class_id_idx on public.activities(class_id);
create index if not exists announcements_class_id_idx on public.announcements(class_id);
create index if not exists visits_timestamp_idx on public.visits(timestamp desc);
-- Configure RLS policies for Supabase Auth, or use a server-only SUPABASE_SERVICE_ROLE_KEY. Do not expose that key to the frontend.
